<a href="https://colab.research.google.com/github/lucabmanning/563-luca/blob/main/luca_lattice_mc.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Week 3: Monte Carlo Code

**Python notebook that:**
1.   Can perform NVT simulations of square-lattice particles.
2.   Obeys detailed balance.
3. Uses periodic boundary conditions.
4.   Demonstrates a temperature below which you observe particles clustering together.
5.   Includes some measurements of which system sizes are too large to be practical on google colab.



---



In [72]:
import numpy as np
import matplotlib.pyplot as plt
import random

# GRID
class Grid():
# needs a size and have particles that sit in it
# a helper function that gives me neighbors of a site will be helpful
# grid class defines a blueprint for creating objects representing the
    # simulation grid.
    def __init__(self,L,N):
# def will define a new function
# the two underscores before and after init means dunder?
# __init__ is a special method called the constructor.
#  It's executed automatically when you create a new Grid object.
        self.sites = np.zeros((L,L)) # Use np.zeros instead of numpy.zeros
# need to put N particles in the system
        self.N = N
# stores the number of particles in the grid object
        self.particles = []
# initializes empty list to store particle objects
        # The for loop was outside the __init__ method
        # Indenting it to be part of the __init__ method
        for i in range(self.N):
            self.particles.append(particle(self))
            self.particles[-1].location = [0,0]
        # self.lattice = np.random.choice([-1, 1], size=(L, L))

    def display(self):
        plt.imshow(self.lattice, cmap='gray')
        plt.axis('off')
        plt.show()

# PARTICLES
class particle():
# Calculate distances
    def __init__(self,system):
      self.system = system
      self.location = [0,0]

    def get_neighbors(self):
      for d in [ (1,0), (0,-1), (-1,0), (0,1)]:
  #up, down, left, right
        new_location = [self.location[0] + d[0], self.location[1] + d[1]]
        print (d + tuple(self.location))
# Alternatively, convert d to a list:
        # print(list(d) + self.location)

# CALCULATE ENERGY OF A CONFIGURATION (microstate)
    def calculate_energy(self):
        energy = 0
        for particle in self.particles:
            x, y = particle.location
            for dx, dy in [(1, 0), (0, 1)]:  # Check neighbors to the right and down
                nx, ny = (x + dx) % self.sites.shape[0], (y + dy) % self.sites.shape[1]  # Periodic boundary conditions
                neighbor = self.find_particle_at_location([nx, ny]) #Find particle at the neighbor location
                if neighbor:
                    energy -= particle.spin * neighbor.spin  # Ising-like interaction
        return energy/2 #Avoid double counting

    def find_particle_at_location(self, location):
        for particle in self.particles:
            if particle.location == location:
                return particle
        return None #If location is empty

In [74]:
# tests
sample_system = Grid(10, 20)
# sample_system.display()
print(sample_system.N)
print(sample_system.sites)
print(sample_system.particles[-1].get_neighbors())

grid = Grid(L=10, N=20)  # Create a 10x10 grid with 20 particles
# energy = grid.calculate_energy()  # Calculate the energy of the current configuration
# print(f"Energy of the configuration: {energy}")

20
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
(1, 0, 0, 0)
(0, -1, 0, 0)
(-1, 0, 0, 0)
(0, 1, 0, 0)
None
